config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :car_brands
  resources :dealerships
  root to: "dashboard#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car_brand.rb
class CarBrand < ApplicationRecord
  has_many :cars, dependent: :destroy
end

app/controllers/car_brands_controller.rb
class CarBrandsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only
  before_action :set_car_brand, only: %i[ show edit update destroy ]

  # GET /car_brands or /car_brands.json
  def index
    @car_brands = CarBrand.all
  end

  # GET /car_brands/1 or /car_brands/1.json
  def show
  end

  # GET /car_brands/new
  def new
    @car_brand = CarBrand.new
  end

  # GET /car_brands/1/edit
  def edit
  end

  # POST /car_brands or /car_brands.json
  def create
    @car_brand = CarBrand.new(car_brand_params)

    respond_to do |format|
      if @car_brand.save
        format.html { redirect_to @car_brand, notice: "Car brand was successfully created." }
        format.json { render :show, status: :created, location: @car_brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_brands/1 or /car_brands/1.json
  def update
    respond_to do |format|
      if @car_brand.update(car_brand_params)
        format.html { redirect_to @car_brand, notice: "Car brand was successfully updated." }
        format.json { render :show, status: :ok, location: @car_brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_brands/1 or /car_brands/1.json
  def destroy
    @car_brand.destroy
    respond_to do |format|
      format.html { redirect_to car_brands_url, notice: "Car brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_brand
      @car_brand = CarBrand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_brand_params
      params.require(:car_brand).permit(:name)
    end
end

app/helpers/car_brands_helper.rb
module CarBrandsHelper
end

app/views/car_brands/_form.html.erb
<%= form_with(model: car_brand) do |form| %>
  <% if car_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car_brand.errors.count, "error") %> prohibited this car_brand from being saved:</h2>

      <ul>
        <% car_brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/car_brands/edit.html.erb
<h1>Editing Car Brand</h1>

<%= render 'form', car_brand: @car_brand %>

<%= link_to 'Show', @car_brand %> |
<%= link_to 'Back', car_brands_path %>

app/views/car_brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Car Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_brands.each do |car_brand| %>
      <tr>
        <td><%= car_brand.name %></td>
        <td><%= link_to 'Show', car_brand %></td>
        <td><%= link_to 'Edit', edit_car_brand_path(car_brand) %></td>
        <td><%= link_to 'Destroy', car_brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car Brand', new_car_brand_path %>

app/views/car_brands/new.html.erb
<h1>New Car Brand</h1>

<%= render 'form', car_brand: @car_brand %>

<%= link_to 'Back', car_brands_path %>

app/views/car_brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car_brand.name %>
</p>

<%= link_to 'Edit', edit_car_brand_path(@car_brand) %> |
<%= link_to 'Back', car_brands_path %>