config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :car_brands
  resources :dealerships
  root to: "dashboard#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  enum kind: [:new, :used], _prefix: :kind
  belongs_to :car_brand
  has_many :car_dealerships, dependent: :destroy
  has_many :dealerships, through: :car_dealerships
  accepts_nested_attributes_for :dealerships

  def dealerships_attributes=(dealership_attributes)
    dealership_attributes.values.each do |dealership_attribute|
      dealership = Dealership.find_or_create_by(dealership_attribute)
      self.dealerships << dealership
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, except: %i[index show]
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :get_brands_for_select, only: %i[new edit]
  # GET /cars or /cars.json
  def index
    @cars = []
    current_user.dealerships.includes(:cars).each do |dealership|
      @cars = dealership.cars
    end
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_brands_for_select
      @brands = CarBrand.all.map { |brand| [brand.name, brand.id]}
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:car_brand_id, :model, :color, :name, :doors, :price, :kind, :quantity, dealership_ids:[], dealerships_attributes: [:name])
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

   <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :car_brand_id %>
    <%= form.collection_select :car_brand_id, CarBrand.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= form.select :kind, options_for_select(
      Car.kinds.map { |key, value| [key.titleize, Car.kinds.key(value)] }, @car.kind) %>
  </div>

  <div class="field">
    <%= form.label :doors %>
    <%= form.number_field :doors %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class='field'>
    <%= form.label :dealerships %>
    <%= form.collection_check_boxes :dealership_ids, Dealership.all, :id, :name %>
    <%= form.fields_for :dealerships, car.dealerships.build do |deal_fields| %>
      <h3>New Dealership</h3>
      <div class="field">
        <%= deal_fields.label :name %>
        <%= deal_fields.text_field :name %>
      </div>
      <div class="field">
        <%= deal_fields.label :address %>
        <%= deal_fields.text_area :address %>
      </div>
    <% end %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th>Color</th>
      <th>Car brand</th>
      <th>Doors</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Dealerships</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.car_brand.name %></td>
        <td><%= car.doors %></td>
        <td><%= number_to_currency(car.price) %></td>

        <td><%= car.quantity %></td>
        <td><%= car.dealerships.map { |deal| deal.name }.join(", ") %></td>
        <td><%= car.kind %></td>
        <td><%= link_to 'Show', car %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_car_path(car) %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path if current_user.admin? %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car brand:</strong>
  <%= @car.car_brand_id %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @car.doors %>
</p>

<%= link_to 'Edit', edit_car_path(@car) if current_user.admin? %> |
<%= link_to 'Back', cars_path %>